/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './hello-ionic';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '../../providers/webMethod';
import * as import10 from '../../providers/function';
import * as import11 from '@angular/core/src/metadata/view';
import * as import12 from '@angular/core/src/linker/component_factory';
import * as import13 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import14 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import15 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import16 from '../../node_modules/ionic-angular/components/menu/menu-toggle.ngfactory';
import * as import17 from '../../node_modules/ionic-angular/components/toolbar/toolbar-item.ngfactory';
import * as import18 from '@angular/core/src/linker/query_list';
import * as import19 from '../../node_modules/ionic-angular/components/icon/icon.ngfactory';
import * as import20 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import21 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import22 from '../../node_modules/ionic-angular/components/list/list.ngfactory';
import * as import23 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import24 from '../../node_modules/ionic-angular/components/label/label.ngfactory';
import * as import25 from '../../node_modules/ionic-angular/components/select/select.ngfactory';
import * as import26 from '../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import27 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import28 from '../../node_modules/ionic-angular/components/option/option.ngfactory';
import * as import29 from '../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import30 from '../../node_modules/ionic-angular/components/infinite-scroll/infinite-scroll.ngfactory';
import * as import31 from '../../node_modules/ionic-angular/components/infinite-scroll/infinite-scroll-content.ngfactory';
import * as import32 from 'ionic-angular/config/config';
import * as import33 from '@angular/core/src/linker/element_ref';
import * as import34 from 'ionic-angular/navigation/view-controller';
import * as import35 from 'ionic-angular/components/app/app';
import * as import36 from 'ionic-angular/components/menu/menu-controller';
import * as import37 from 'ionic-angular/components/toolbar/toolbar';
import * as import38 from 'ionic-angular/util/keyboard';
import * as import39 from '@angular/core/src/zone/ng_zone';
import * as import40 from 'ionic-angular/components/tabs/tabs';
import * as import41 from 'ionic-angular/gestures/gesture-controller';
import * as import42 from 'ionic-angular/util/form';
import * as import43 from 'ionic-angular/components/item/item-reorder';
import * as import44 from '@angular/core/src/linker/template_ref';
import * as import45 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import46 from 'ionic-angular/components/icon/icon';
import * as import47 from 'ionic-angular/components/button/button';
import * as import48 from 'ionic-angular/components/menu/menu-toggle';
import * as import49 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import50 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import51 from 'ionic-angular/components/navbar/navbar';
import * as import52 from 'ionic-angular/components/label/label';
import * as import53 from 'ionic-angular/components/option/option';
import * as import54 from '@angular/common/src/directives/ng_for';
import * as import55 from 'ionic-angular/components/select/select';
import * as import56 from '@angular/forms/src/directives/control_value_accessor';
import * as import57 from '@angular/forms/src/directives/ng_model';
import * as import58 from '@angular/forms/src/directives/ng_control';
import * as import59 from '@angular/forms/src/directives/ng_control_status';
import * as import60 from 'ionic-angular/components/item/item';
import * as import61 from 'ionic-angular/components/list/list';
import * as import62 from 'ionic-angular/components/infinite-scroll/infinite-scroll-content';
import * as import63 from 'ionic-angular/components/infinite-scroll/infinite-scroll';
import * as import64 from 'ionic-angular/components/content/content';
import * as import65 from '../../node_modules/ionic-angular/components/card/card.ngfactory';
import * as import66 from '../../node_modules/ionic-angular/components/grid/grid.ngfactory';
import * as import67 from 'ionic-angular/components/card/card';
import * as import68 from 'ionic-angular/components/grid/grid';
import * as import69 from '@angular/core/src/security';
export class Wrapper_MainTab2 {
  context:import0.MainTab2;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any) {
    this.changed = false;
    this.context = new import0.MainTab2(p0,p1,p2);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_MainTab2_Host:import2.RenderComponentType = (null as any);
class _View_MainTab2_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _MainTab2_0_4:Wrapper_MainTab2;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_MainTab2_Host0,renderType_MainTab2_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('hello-ionic-page',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_MainTab20(this.viewUtils,this.injector(0),this._appEl_0);
    this._MainTab2_0_4 = new Wrapper_MainTab2(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.WebMethod),this.parentInjector.get(import10.GlobalFunction));
    this._appEl_0.initComponent(this._MainTab2_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._MainTab2_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.MainTab2) && (0 === requestNodeIndex))) { return this._MainTab2_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._MainTab2_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_MainTab2_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_MainTab2_Host === (null as any))) { (renderType_MainTab2_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_MainTab2_Host0(viewUtils,parentInjector,declarationEl);
}
export const MainTab2NgFactory:import12.ComponentFactory<import0.MainTab2> = new import12.ComponentFactory<import0.MainTab2>('hello-ionic-page',viewFactory_MainTab2_Host0,import0.MainTab2);
const styles_MainTab2:any[] = ([] as any[]);
var renderType_MainTab2:import2.RenderComponentType = (null as any);
class _View_MainTab20 extends import1.AppView<import0.MainTab2> {
  _el_0:any;
  _Header_0_3:import13.Wrapper_Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Navbar_2_4:import14.Wrapper_Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _Button_4_4:import15.Wrapper_Button;
  _MenuToggle_4_5:import16.Wrapper_MenuToggle;
  _ToolbarItem_4_6:import17.Wrapper_ToolbarItem;
  _query_Button_4_0:import18.QueryList<any>;
  _text_5:any;
  _el_6:any;
  _Icon_6_3:import19.Wrapper_Icon;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import3.AppElement;
  _ToolbarTitle_9_4:import20.Wrapper_ToolbarTitle;
  _text_10:any;
  _el_11:any;
  _Icon_11_3:import19.Wrapper_Icon;
  _text_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  /*private*/ _appEl_16:import3.AppElement;
  _Content_16_4:import21.Wrapper_Content;
  _text_17:any;
  _el_18:any;
  _List_18_3:import22.Wrapper_List;
  _text_19:any;
  _el_20:any;
  /*private*/ _appEl_20:import3.AppElement;
  _Item_20_4:import23.Wrapper_Item;
  _ItemContent_20_5:import23.Wrapper_ItemContent;
  _query_Label_20_0:import18.QueryList<any>;
  _query_Button_20_1:import18.QueryList<any>;
  _query_Icon_20_2:import18.QueryList<any>;
  _text_21:any;
  _el_22:any;
  _Label_22_3:import24.Wrapper_Label;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  /*private*/ _appEl_25:import3.AppElement;
  _Select_25_4:import25.Wrapper_Select;
  _NG_VALUE_ACCESSOR_25_5:any[];
  _NgModel_25_6:import26.Wrapper_NgModel;
  _NgControl_25_7:any;
  _NgControlStatus_25_8:import27.Wrapper_NgControlStatus;
  _query_Option_25_0:import18.QueryList<any>;
  _text_26:any;
  _el_27:any;
  _Option_27_3:import28.Wrapper_Option;
  _text_28:any;
  _text_29:any;
  _anchor_30:any;
  /*private*/ _appEl_30:import3.AppElement;
  _TemplateRef_30_5:any;
  _NgFor_30_6:import29.Wrapper_NgFor;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _anchor_35:any;
  /*private*/ _appEl_35:import3.AppElement;
  _TemplateRef_35_5:any;
  _NgFor_35_6:import29.Wrapper_NgFor;
  _text_36:any;
  _el_37:any;
  _InfiniteScroll_37_3:import30.Wrapper_InfiniteScroll;
  _text_38:any;
  _el_39:any;
  /*private*/ _appEl_39:import3.AppElement;
  _InfiniteScrollContent_39_4:import31.Wrapper_InfiniteScrollContent;
  _text_40:any;
  _text_41:any;
  _text_42:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_28:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_MainTab20,renderType_MainTab2,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import13.Wrapper_Header(this.parentInjector.get(import32.Config),new import33.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import34.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import14.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import14.Wrapper_Navbar(this.parentInjector.get(import35.App),this.parentInjector.get(import34.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import32.Config),new import33.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_4,'ion-button','');
    this.renderer.setElementAttribute(this._el_4,'menuToggle','');
    this._appEl_4 = new import3.AppElement(4,2,this,this._el_4);
    var compView_4:any = import15.viewFactory_Button0(this.viewUtils,this.injector(4),this._appEl_4);
    this._Button_4_4 = new import15.Wrapper_Button('','',this.parentInjector.get(import32.Config),new import33.ElementRef(this._el_4),this.renderer);
    this._MenuToggle_4_5 = new import16.Wrapper_MenuToggle(this.parentInjector.get(import36.MenuController),new import33.ElementRef(this._el_4),this.parentInjector.get(import34.ViewController,(null as any)),this._Navbar_2_4.context);
    this._ToolbarItem_4_6 = new import17.Wrapper_ToolbarItem(this.parentInjector.get(import32.Config),new import33.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import37.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._query_Button_4_0 = new import18.QueryList<any>();
    this._appEl_4.initComponent(this._Button_4_4.context,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_6,'name','menu');
    this.renderer.setElementAttribute(this._el_6,'role','img');
    this._Icon_6_3 = new import19.Wrapper_Icon(this.parentInjector.get(import32.Config),new import33.ElementRef(this._el_6),this.renderer);
    this._text_7 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_4.create(this._Button_4_4.context,[([] as any[]).concat([
        this._text_5,
        this._el_6,
        this._text_7
      ]
    )],(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_9 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_9 = new import3.AppElement(9,2,this,this._el_9);
    var compView_9:any = import20.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(9),this._appEl_9);
    this._ToolbarTitle_9_4 = new import20.Wrapper_ToolbarTitle(this.parentInjector.get(import32.Config),new import33.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import37.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._appEl_9.initComponent(this._ToolbarTitle_9_4.context,([] as any[]),compView_9);
    this._text_10 = this.renderer.createText((null as any),'Symbol List\n        ',(null as any));
    this._el_11 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_11,'name','refresh-circle');
    this.renderer.setElementAttribute(this._el_11,'role','img');
    this._Icon_11_3 = new import19.Wrapper_Icon(this.parentInjector.get(import32.Config),new import33.ElementRef(this._el_11),this.renderer);
    this._text_12 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_9.create(this._ToolbarTitle_9_4.context,[([] as any[]).concat([
        this._text_10,
        this._el_11,
        this._text_12
      ]
    )],(null as any));
    this._text_13 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    compView_2.create(this._Navbar_2_4.context,[
      ([] as any[]).concat([this._el_4]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._text_8,
        this._el_9,
        this._text_13
      ]
      )
    ]
    ,(null as any));
    this._text_14 = this.renderer.createText(this._el_0,'\n\n',(null as any));
    this._text_15 = this.renderer.createText(parentRenderNode,'\n\n\n',(null as any));
    this._el_16 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_16,'padding','');
    this._appEl_16 = new import3.AppElement(16,(null as any),this,this._el_16);
    var compView_16:any = import21.viewFactory_Content0(this.viewUtils,this.injector(16),this._appEl_16);
    this._Content_16_4 = new import21.Wrapper_Content(this.parentInjector.get(import32.Config),new import33.ElementRef(this._el_16),this.renderer,this.parentInjector.get(import35.App),this.parentInjector.get(import38.Keyboard),this.parentInjector.get(import39.NgZone),this.parentInjector.get(import34.ViewController,(null as any)),this.parentInjector.get(import40.Tabs,(null as any)));
    this._appEl_16.initComponent(this._Content_16_4.context,([] as any[]),compView_16);
    this._text_17 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_18 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this._List_18_3 = new import22.Wrapper_List(this.parentInjector.get(import32.Config),new import33.ElementRef(this._el_18),this.renderer,this.parentInjector.get(import41.GestureController));
    this._text_19 = this.renderer.createText(this._el_18,'\n    ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_18,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_20,'class','item item-block');
    this._appEl_20 = new import3.AppElement(20,18,this,this._el_20);
    var compView_20:any = import23.viewFactory_Item0(this.viewUtils,this.injector(20),this._appEl_20);
    this._Item_20_4 = new import23.Wrapper_Item(this.parentInjector.get(import42.Form),this.parentInjector.get(import32.Config),new import33.ElementRef(this._el_20),this.renderer,this.parentInjector.get(import43.ItemReorder,(null as any)));
    this._ItemContent_20_5 = new import23.Wrapper_ItemContent();
    this._query_Label_20_0 = new import18.QueryList<any>();
    this._query_Button_20_1 = new import18.QueryList<any>();
    this._query_Icon_20_2 = new import18.QueryList<any>();
    this._appEl_20.initComponent(this._Item_20_4.context,([] as any[]),compView_20);
    this._text_21 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_22 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_22_3 = new import24.Wrapper_Label(this.parentInjector.get(import32.Config),new import33.ElementRef(this._el_22),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_23 = this.renderer.createText(this._el_22,'Type123',(null as any));
    this._text_24 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_25 = this.renderer.createElement((null as any),'ion-select',(null as any));
    this.renderer.setElementAttribute(this._el_25,'multiple','true');
    this._appEl_25 = new import3.AppElement(25,20,this,this._el_25);
    var compView_25:any = import25.viewFactory_Select0(this.viewUtils,this.injector(25),this._appEl_25);
    this._Select_25_4 = new import25.Wrapper_Select(this.parentInjector.get(import35.App),this.parentInjector.get(import42.Form),this.parentInjector.get(import32.Config),new import33.ElementRef(this._el_25),this.renderer,this._Item_20_4.context,this.parentInjector.get(import8.NavController,(null as any)));
    this._NG_VALUE_ACCESSOR_25_5 = [this._Select_25_4.context];
    this._NgModel_25_6 = new import26.Wrapper_NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_25_5);
    this._NgControl_25_7 = this._NgModel_25_6.context;
    this._NgControlStatus_25_8 = new import27.Wrapper_NgControlStatus(this._NgControl_25_7);
    this._query_Option_25_0 = new import18.QueryList<any>();
    this._appEl_25.initComponent(this._Select_25_4.context,([] as any[]),compView_25);
    this._text_26 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_27 = this.renderer.createElement((null as any),'ion-option',(null as any));
    this.renderer.setElementAttribute(this._el_27,'ng-selected','true');
    this.renderer.setElementAttribute(this._el_27,'value','');
    this._Option_27_3 = new import28.Wrapper_Option(new import33.ElementRef(this._el_27));
    this._text_28 = this.renderer.createText(this._el_27,'ALL',(null as any));
    this._text_29 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._anchor_30 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_30 = new import3.AppElement(30,25,this,this._anchor_30);
    this._TemplateRef_30_5 = new import44.TemplateRef_(this._appEl_30,viewFactory_MainTab21);
    this._NgFor_30_6 = new import29.Wrapper_NgFor(this._appEl_30.vcRef,this._TemplateRef_30_5,this.parentInjector.get(import45.IterableDiffers),this.ref);
    this._text_31 = this.renderer.createText((null as any),'\n      ',(null as any));
    compView_25.create(this._Select_25_4.context,([] as any[]),(null as any));
    this._text_32 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_20_0.reset([this._Label_22_3.context]);
    this._Item_20_4.context.contentLabel = this._query_Label_20_0.first;
    compView_20.create(this._Item_20_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_22]),
      ([] as any[]).concat([
        this._text_21,
        this._text_24,
        this._text_32
      ]
      ),
      ([] as any[]).concat([this._el_25]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_33 = this.renderer.createText(this._el_18,'\n  ',(null as any));
    this._text_34 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._anchor_35 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_35 = new import3.AppElement(35,16,this,this._anchor_35);
    this._TemplateRef_35_5 = new import44.TemplateRef_(this._appEl_35,viewFactory_MainTab22);
    this._NgFor_35_6 = new import29.Wrapper_NgFor(this._appEl_35.vcRef,this._TemplateRef_35_5,this.parentInjector.get(import45.IterableDiffers),this.ref);
    this._text_36 = this.renderer.createText((null as any),'\n\n\n   ',(null as any));
    this._el_37 = this.renderer.createElement((null as any),'ion-infinite-scroll',(null as any));
    this._InfiniteScroll_37_3 = new import30.Wrapper_InfiniteScroll(this._Content_16_4.context,this.parentInjector.get(import39.NgZone),new import33.ElementRef(this._el_37));
    this._text_38 = this.renderer.createText(this._el_37,'\n     ',(null as any));
    this._el_39 = this.renderer.createElement(this._el_37,'ion-infinite-scroll-content',(null as any));
    this._appEl_39 = new import3.AppElement(39,37,this,this._el_39);
    var compView_39:any = import31.viewFactory_InfiniteScrollContent0(this.viewUtils,this.injector(39),this._appEl_39);
    this._InfiniteScrollContent_39_4 = new import31.Wrapper_InfiniteScrollContent(this._InfiniteScroll_37_3.context,this.parentInjector.get(import32.Config));
    this._appEl_39.initComponent(this._InfiniteScrollContent_39_4.context,([] as any[]),compView_39);
    compView_39.create(this._InfiniteScrollContent_39_4.context,([] as any[]),(null as any));
    this._text_40 = this.renderer.createText(this._el_37,'\n   ',(null as any));
    this._text_41 = this.renderer.createText((null as any),'\n\n',(null as any));
    compView_16.create(this._Content_16_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_17,
        this._el_18,
        this._text_34,
        this._appEl_35,
        this._text_36,
        this._el_37,
        this._text_41
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_42 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_4,'click',this.eventHandler(this._handle_click_4_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_9,'click',this.eventHandler(this._handle_click_9_0.bind(this)));
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_25,'ngModelChange',this.eventHandler(this._handle_ngModelChange_25_0.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_25,'ionChange',this.eventHandler(this._handle_ionChange_25_1.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_25,'click',this.eventHandler(this._handle_click_25_2.bind(this)));
    var disposable_5:Function = this.renderer.listen(this._el_25,'keyup.space',this.eventHandler(this._handle_keyup_space_25_3.bind(this)));
    this._expr_16 = import7.UNINITIALIZED;
    const subscription_0:any = this._Select_25_4.context.ionChange.subscribe(this.eventHandler(this._handle_ionChange_25_1.bind(this)));
    const subscription_1:any = this._NgModel_25_6.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_25_0.bind(this)));
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_20 = import7.UNINITIALIZED;
    this._expr_21 = import7.UNINITIALIZED;
    this._expr_22 = import7.UNINITIALIZED;
    this._expr_23 = import7.UNINITIALIZED;
    var disposable_6:Function = this.renderer.listen(this._el_37,'ionInfinite',this.eventHandler(this._handle_ionInfinite_37_0.bind(this)));
    const subscription_2:any = this._InfiniteScroll_37_3.context.ionInfinite.subscribe(this.eventHandler(this._handle_ionInfinite_37_0.bind(this)));
    this._expr_28 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._anchor_30,
      this._text_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._anchor_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._text_41,
      this._text_42
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6
    ]
    ,[
      subscription_0,
      subscription_1,
      subscription_2
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import46.Icon) && (6 === requestNodeIndex))) { return this._Icon_6_3.context; }
    if (((token === import47.Button) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Button_4_4.context; }
    if (((token === import48.MenuToggle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._MenuToggle_4_5.context; }
    if (((token === import49.ToolbarItem) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._ToolbarItem_4_6.context; }
    if (((token === import46.Icon) && (11 === requestNodeIndex))) { return this._Icon_11_3.context; }
    if (((token === import50.ToolbarTitle) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._ToolbarTitle_9_4.context; }
    if (((token === import51.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._Navbar_2_4.context; }
    if (((token === import37.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._Header_0_3.context; }
    if (((token === import52.Label) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._Label_22_3.context; }
    if (((token === import53.Option) && ((27 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._Option_27_3.context; }
    if (((token === import44.TemplateRef) && (30 === requestNodeIndex))) { return this._TemplateRef_30_5; }
    if (((token === import54.NgFor) && (30 === requestNodeIndex))) { return this._NgFor_30_6.context; }
    if (((token === import55.Select) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._Select_25_4.context; }
    if (((token === import56.NG_VALUE_ACCESSOR) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._NG_VALUE_ACCESSOR_25_5; }
    if (((token === import57.NgModel) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._NgModel_25_6.context; }
    if (((token === import58.NgControl) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._NgControl_25_7; }
    if (((token === import59.NgControlStatus) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._NgControlStatus_25_8.context; }
    if (((token === import60.Item) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._Item_20_4.context; }
    if (((token === import60.ItemContent) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._ItemContent_20_5.context; }
    if (((token === import61.List) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._List_18_3.context; }
    if (((token === import44.TemplateRef) && (35 === requestNodeIndex))) { return this._TemplateRef_35_5; }
    if (((token === import54.NgFor) && (35 === requestNodeIndex))) { return this._NgFor_35_6.context; }
    if (((token === import62.InfiniteScrollContent) && (39 === requestNodeIndex))) { return this._InfiniteScrollContent_39_4.context; }
    if (((token === import63.InfiniteScroll) && ((37 <= requestNodeIndex) && (requestNodeIndex <= 40)))) { return this._InfiniteScroll_37_3.context; }
    if (((token === import64.Content) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 41)))) { return this._Content_16_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this._Navbar_2_4.detectChangesInternal(this,this._el_2,throwOnChange);
    if (this._Button_4_4.detectChangesInternal(this,this._el_4,throwOnChange)) { this._appEl_4.componentView.markAsCheckOnce(); }
    const currVal_3:any = '';
    this._MenuToggle_4_5.check_menuToggle(currVal_3,throwOnChange,false);
    this._MenuToggle_4_5.detectChangesInternal(this,this._el_4,throwOnChange);
    this._ToolbarItem_4_6.detectChangesInternal(this,this._el_4,throwOnChange);
    const currVal_5:any = 'menu';
    this._Icon_6_3.check_name(currVal_5,throwOnChange,false);
    this._Icon_6_3.detectChangesInternal(this,this._el_6,throwOnChange);
    if (this._ToolbarTitle_9_4.detectChangesInternal(this,this._el_9,throwOnChange)) { this._appEl_9.componentView.markAsCheckOnce(); }
    const currVal_8:any = 'refresh-circle';
    this._Icon_11_3.check_name(currVal_8,throwOnChange,false);
    this._Icon_11_3.detectChangesInternal(this,this._el_11,throwOnChange);
    if (this._Content_16_4.detectChangesInternal(this,this._el_16,throwOnChange)) { this._appEl_16.componentView.markAsCheckOnce(); }
    this._List_18_3.detectChangesInternal(this,this._el_18,throwOnChange);
    if (this._Item_20_4.detectChangesInternal(this,this._el_20,throwOnChange)) { this._appEl_20.componentView.markAsCheckOnce(); }
    this._ItemContent_20_5.detectChangesInternal(this,this._el_20,throwOnChange);
    this._Label_22_3.detectChangesInternal(this,this._el_22,throwOnChange);
    const currVal_15:any = 'true';
    this._Select_25_4.check_multiple(currVal_15,throwOnChange,false);
    this._Select_25_4.detectChangesInternal(this,this._el_25,throwOnChange);
    const currVal_17:any = this.context.type;
    this._NgModel_25_6.check_model(currVal_17,throwOnChange,false);
    this._NgModel_25_6.detectChangesInternal(this,this._el_25,throwOnChange);
    this._NgControlStatus_25_8.detectChangesInternal(this,this._el_25,throwOnChange);
    const currVal_24:any = '';
    this._Option_27_3.check_value(currVal_24,throwOnChange,false);
    this._Option_27_3.detectChangesInternal(this,this._el_27,throwOnChange);
    const currVal_25:any = this.context.symboltypes;
    this._NgFor_30_6.check_ngForOf(currVal_25,throwOnChange,false);
    this._NgFor_30_6.detectChangesInternal(this,this._anchor_30,throwOnChange);
    const currVal_26:any = this.context.symbols;
    this._NgFor_35_6.check_ngForOf(currVal_26,throwOnChange,false);
    this._NgFor_35_6.detectChangesInternal(this,this._anchor_35,throwOnChange);
    this._InfiniteScroll_37_3.detectChangesInternal(this,this._el_37,throwOnChange);
    this._InfiniteScrollContent_39_4.detectChangesInternal(this,this._el_39,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_4_0.dirty) {
        this._query_Button_4_0.reset([this._Button_4_4.context]);
        this._ToolbarItem_4_6.context._buttons = this._query_Button_4_0;
        this._query_Button_4_0.notifyOnChanges();
      }
      if (this._query_Option_25_0.dirty) {
        this._query_Option_25_0.reset([
          this._Option_27_3.context,
          this._appEl_30.mapNestedViews(_View_MainTab21,(nestedView:_View_MainTab21):any => {
            return [nestedView._Option_0_3.context];
          })
        ]
        );
        this._Select_25_4.context.options = this._query_Option_25_0;
        this._query_Option_25_0.notifyOnChanges();
      }
      if (this._query_Button_20_1.dirty) {
        this._query_Button_20_1.reset(([] as any[]));
        this._Item_20_4.context._buttons = this._query_Button_20_1;
        this._query_Button_20_1.notifyOnChanges();
      }
      if (this._query_Icon_20_2.dirty) {
        this._query_Icon_20_2.reset(([] as any[]));
        this._Item_20_4.context._icons = this._query_Icon_20_2;
        this._query_Icon_20_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_4_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Select_25_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_20_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._InfiniteScroll_37_3.context.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_2_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_4:any = this._MenuToggle_4_5.context.isHidden;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_4,'hidden',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_6:any = this._Icon_6_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_6,'hide',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_9:any = this._Icon_11_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_11,'hide',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._Content_16_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_16,'statusbar-padding',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_16:any = this._Select_25_4.context._disabled;
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_25,'select-disabled',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_18:any = this._NgControlStatus_25_8.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_25,'ng-untouched',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this._NgControlStatus_25_8.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_25,'ng-touched',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = this._NgControlStatus_25_8.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_25,'ng-pristine',currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_21:any = this._NgControlStatus_25_8.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setElementClass(this._el_25,'ng-dirty',currVal_21);
      this._expr_21 = currVal_21;
    }
    const currVal_22:any = this._NgControlStatus_25_8.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setElementClass(this._el_25,'ng-valid',currVal_22);
      this._expr_22 = currVal_22;
    }
    const currVal_23:any = this._NgControlStatus_25_8.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this.renderer.setElementClass(this._el_25,'ng-invalid',currVal_23);
      this._expr_23 = currVal_23;
    }
    const currVal_28:any = this._InfiniteScrollContent_39_4.context.inf.state;
    if (import4.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementAttribute(this._el_39,'state',((currVal_28 == (null as any))? (null as any): currVal_28.toString()));
      this._expr_28 = currVal_28;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_6_3.context.ngOnDestroy();
    this._Icon_11_3.context.ngOnDestroy();
    this._Select_25_4.context.ngOnDestroy();
    this._NgModel_25_6.context.ngOnDestroy();
    this._InfiniteScroll_37_3.context.ngOnDestroy();
    this._Content_16_4.context.ngOnDestroy();
  }
  private _handle_click_4_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MenuToggle_4_5.context.toggle()) !== false);
    return (true && pd_0);
  }
  private _handle_click_9_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.refresh(this.context)) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_25_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.type = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_ionChange_25_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.updatelist(this.context)) !== false);
    return (true && pd_0);
  }
  private _handle_click_25_2($event:any):boolean {
    this._appEl_25.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Select_25_4.context._click($event)) !== false);
    return (true && pd_0);
  }
  private _handle_keyup_space_25_3($event:any):boolean {
    this._appEl_25.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Select_25_4.context._keyup()) !== false);
    return (true && pd_0);
  }
  private _handle_ionInfinite_37_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.doInfinite($event)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_MainTab20(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.MainTab2> {
  if ((renderType_MainTab2 === (null as any))) { (renderType_MainTab2 = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,styles_MainTab2,{})); }
  return new _View_MainTab20(viewUtils,parentInjector,declarationEl);
}
class _View_MainTab21 extends import1.AppView<any> {
  _el_0:any;
  _Option_0_3:import28.Wrapper_Option;
  _text_1:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_MainTab21,renderType_MainTab2,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-option',(null as any));
    this._Option_0_3 = new import28.Wrapper_Option(new import33.ElementRef(this._el_0));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._expr_1 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import53.Option) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._Option_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = import4.interpolate(1,'',this.context.$implicit.type_id,'');
    this._Option_0_3.check_value(currVal_0,throwOnChange,false);
    this._Option_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = import4.interpolate(1,'',this.context.$implicit.type,'');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  dirtyParentQueriesInternal():void {
    (<_View_MainTab20>this.parent)._query_Option_25_0.setDirty();
  }
}
function viewFactory_MainTab21(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_MainTab21(viewUtils,parentInjector,declarationEl);
}
class _View_MainTab22 extends import1.AppView<any> {
  _el_0:any;
  _Card_0_3:import65.Wrapper_Card;
  _text_1:any;
  _el_2:any;
  _CardHeader_2_3:import65.Wrapper_CardHeader;
  _text_3:any;
  _text_4:any;
  _text_5:any;
  _el_6:any;
  _CardContent_6_3:import65.Wrapper_CardContent;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _Row_9_3:import66.Wrapper_Row;
  _text_10:any;
  _el_11:any;
  _Col_11_3:import66.Wrapper_Col;
  _text_12:any;
  _el_13:any;
  /*private*/ _appEl_13:import3.AppElement;
  _Button_13_4:import15.Wrapper_Button;
  _text_14:any;
  _el_15:any;
  _Icon_15_3:import19.Wrapper_Icon;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _Col_19_3:import66.Wrapper_Col;
  _text_20:any;
  _el_21:any;
  /*private*/ _appEl_21:import3.AppElement;
  _Button_21_4:import15.Wrapper_Button;
  _text_22:any;
  _el_23:any;
  _Icon_23_3:import19.Wrapper_Icon;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  _el_27:any;
  _Col_27_3:import66.Wrapper_Col;
  _text_28:any;
  _el_29:any;
  /*private*/ _appEl_29:import3.AppElement;
  _Button_29_4:import15.Wrapper_Button;
  _text_30:any;
  _el_31:any;
  _Icon_31_3:import19.Wrapper_Icon;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_20:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_MainTab22,renderType_MainTab2,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-card',(null as any));
    this.renderer.setElementAttribute(this._el_0,'padding','');
    this._Card_0_3 = new import65.Wrapper_Card(this.parent.parentInjector.get(import32.Config),new import33.ElementRef(this._el_0),this.renderer);
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-card-header',(null as any));
    this._CardHeader_2_3 = new import65.Wrapper_CardHeader(this.parent.parentInjector.get(import32.Config),new import33.ElementRef(this._el_2),this.renderer);
    this._text_3 = this.renderer.createText(this._el_2,'\n\n      ',(null as any));
    this._text_4 = this.renderer.createText(this._el_2,'\n   ',(null as any));
    this._text_5 = this.renderer.createText(this._el_0,'\n     ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_0,'ion-card-content',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','item item-text-wrap ion-card-content');
    this._CardContent_6_3 = new import65.Wrapper_CardContent(this.parent.parentInjector.get(import32.Config),new import33.ElementRef(this._el_6),this.renderer);
    this._text_7 = this.renderer.createText(this._el_6,'\n\n     ',(null as any));
    this._text_8 = this.renderer.createText(this._el_0,'\n\n     ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_0,'ion-row',(null as any));
    this.renderer.setElementAttribute(this._el_9,'no-padding','');
    this._Row_9_3 = new import66.Wrapper_Row();
    this._text_10 = this.renderer.createText(this._el_9,'\n       ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_9,'ion-col',(null as any));
    this._Col_11_3 = new import66.Wrapper_Col();
    this._text_12 = this.renderer.createText(this._el_11,'\n         ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_11,'button',(null as any));
    this.renderer.setElementAttribute(this._el_13,'clear','');
    this.renderer.setElementAttribute(this._el_13,'icon-left','');
    this.renderer.setElementAttribute(this._el_13,'ion-button','');
    this.renderer.setElementAttribute(this._el_13,'small','');
    this._appEl_13 = new import3.AppElement(13,11,this,this._el_13);
    var compView_13:any = import15.viewFactory_Button0(this.viewUtils,this.injector(13),this._appEl_13);
    this._Button_13_4 = new import15.Wrapper_Button((null as any),'',this.parent.parentInjector.get(import32.Config),new import33.ElementRef(this._el_13),this.renderer);
    this._appEl_13.initComponent(this._Button_13_4.context,([] as any[]),compView_13);
    this._text_14 = this.renderer.createText((null as any),'\n           ',(null as any));
    this._el_15 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_15,'name','star');
    this.renderer.setElementAttribute(this._el_15,'role','img');
    this._Icon_15_3 = new import19.Wrapper_Icon(this.parent.parentInjector.get(import32.Config),new import33.ElementRef(this._el_15),this.renderer);
    this._text_16 = this.renderer.createText((null as any),'',(null as any));
      compView_13.create(this._Button_13_4.context,[([] as any[]).concat([
        this._text_14,
        this._el_15,
        this._text_16
      ]
    )],(null as any));
    this._text_17 = this.renderer.createText(this._el_11,'\n       ',(null as any));
    this._text_18 = this.renderer.createText(this._el_9,'\n       ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_9,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_19,'text-center','');
    this._Col_19_3 = new import66.Wrapper_Col();
    this._text_20 = this.renderer.createText(this._el_19,'\n         ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_19,'button',(null as any));
    this.renderer.setElementAttribute(this._el_21,'clear','');
    this.renderer.setElementAttribute(this._el_21,'color','default');
    this.renderer.setElementAttribute(this._el_21,'icon-left','');
    this.renderer.setElementAttribute(this._el_21,'ion-button','');
    this.renderer.setElementAttribute(this._el_21,'small','');
    this._appEl_21 = new import3.AppElement(21,19,this,this._el_21);
    var compView_21:any = import15.viewFactory_Button0(this.viewUtils,this.injector(21),this._appEl_21);
    this._Button_21_4 = new import15.Wrapper_Button((null as any),'',this.parent.parentInjector.get(import32.Config),new import33.ElementRef(this._el_21),this.renderer);
    this._appEl_21.initComponent(this._Button_21_4.context,([] as any[]),compView_21);
    this._text_22 = this.renderer.createText((null as any),'\n           ',(null as any));
    this._el_23 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_23,'name','ios-thumbs-up');
    this.renderer.setElementAttribute(this._el_23,'role','img');
    this._Icon_23_3 = new import19.Wrapper_Icon(this.parent.parentInjector.get(import32.Config),new import33.ElementRef(this._el_23),this.renderer);
    this._text_24 = this.renderer.createText((null as any),'',(null as any));
      compView_21.create(this._Button_21_4.context,[([] as any[]).concat([
        this._text_22,
        this._el_23,
        this._text_24
      ]
    )],(null as any));
    this._text_25 = this.renderer.createText(this._el_19,'\n       ',(null as any));
    this._text_26 = this.renderer.createText(this._el_9,'\n       ',(null as any));
    this._el_27 = this.renderer.createElement(this._el_9,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_27,'text-right','');
    this._Col_27_3 = new import66.Wrapper_Col();
    this._text_28 = this.renderer.createText(this._el_27,'\n         ',(null as any));
    this._el_29 = this.renderer.createElement(this._el_27,'button',(null as any));
    this.renderer.setElementAttribute(this._el_29,'clear','');
    this.renderer.setElementAttribute(this._el_29,'color','default');
    this.renderer.setElementAttribute(this._el_29,'icon-left','');
    this.renderer.setElementAttribute(this._el_29,'ion-button','');
    this.renderer.setElementAttribute(this._el_29,'small','');
    this._appEl_29 = new import3.AppElement(29,27,this,this._el_29);
    var compView_29:any = import15.viewFactory_Button0(this.viewUtils,this.injector(29),this._appEl_29);
    this._Button_29_4 = new import15.Wrapper_Button((null as any),'',this.parent.parentInjector.get(import32.Config),new import33.ElementRef(this._el_29),this.renderer);
    this._appEl_29.initComponent(this._Button_29_4.context,([] as any[]),compView_29);
    this._text_30 = this.renderer.createText((null as any),'\n           ',(null as any));
    this._el_31 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_31,'name','share-alt');
    this.renderer.setElementAttribute(this._el_31,'role','img');
    this._Icon_31_3 = new import19.Wrapper_Icon(this.parent.parentInjector.get(import32.Config),new import33.ElementRef(this._el_31),this.renderer);
    this._text_32 = this.renderer.createText((null as any),'\n           Copy\n         ',(null as any));
      compView_29.create(this._Button_29_4.context,[([] as any[]).concat([
        this._text_30,
        this._el_31,
        this._text_32
      ]
    )],(null as any));
    this._text_33 = this.renderer.createText(this._el_27,'\n       ',(null as any));
    this._text_34 = this.renderer.createText(this._el_9,'\n     ',(null as any));
    this._text_35 = this.renderer.createText(this._el_0,'\n   ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_13,'click',this.eventHandler(this._handle_click_13_0.bind(this)));
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_21,'click',this.eventHandler(this._handle_click_21_0.bind(this)));
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_29,'click',this.eventHandler(this._handle_click_29_0.bind(this)));
    this._expr_20 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._text_35
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import67.CardHeader) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._CardHeader_2_3.context; }
    if (((token === import67.CardContent) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._CardContent_6_3.context; }
    if (((token === import46.Icon) && (15 === requestNodeIndex))) { return this._Icon_15_3.context; }
    if (((token === import47.Button) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._Button_13_4.context; }
    if (((token === import68.Col) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._Col_11_3.context; }
    if (((token === import46.Icon) && (23 === requestNodeIndex))) { return this._Icon_23_3.context; }
    if (((token === import47.Button) && ((21 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._Button_21_4.context; }
    if (((token === import68.Col) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._Col_19_3.context; }
    if (((token === import46.Icon) && (31 === requestNodeIndex))) { return this._Icon_31_3.context; }
    if (((token === import47.Button) && ((29 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._Button_29_4.context; }
    if (((token === import68.Col) && ((27 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._Col_27_3.context; }
    if (((token === import68.Row) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._Row_9_3.context; }
    if (((token === import67.Card) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._Card_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Card_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this._CardHeader_2_3.detectChangesInternal(this,this._el_2,throwOnChange);
    this._CardContent_6_3.detectChangesInternal(this,this._el_6,throwOnChange);
    this._Row_9_3.detectChangesInternal(this,this._el_9,throwOnChange);
    this._Col_11_3.detectChangesInternal(this,this._el_11,throwOnChange);
    const currVal_2:any = '';
    this._Button_13_4.check_small(currVal_2,throwOnChange,false);
    const currVal_3:any = '';
    this._Button_13_4.check_clear(currVal_3,throwOnChange,false);
    const currVal_4:any = import4.interpolate(1,'',this.context.$implicit.favoritecss,'');
    this._Button_13_4.check_color(currVal_4,throwOnChange,false);
    if (this._Button_13_4.detectChangesInternal(this,this._el_13,throwOnChange)) { this._appEl_13.componentView.markAsCheckOnce(); }
    const currVal_5:any = 'star';
    this._Icon_15_3.check_name(currVal_5,throwOnChange,false);
    this._Icon_15_3.detectChangesInternal(this,this._el_15,throwOnChange);
    this._Col_19_3.detectChangesInternal(this,this._el_19,throwOnChange);
    const currVal_9:any = '';
    this._Button_21_4.check_small(currVal_9,throwOnChange,false);
    const currVal_10:any = '';
    this._Button_21_4.check_clear(currVal_10,throwOnChange,false);
    const currVal_11:any = 'default';
    this._Button_21_4.check_color(currVal_11,throwOnChange,false);
    if (this._Button_21_4.detectChangesInternal(this,this._el_21,throwOnChange)) { this._appEl_21.componentView.markAsCheckOnce(); }
    const currVal_12:any = 'ios-thumbs-up';
    this._Icon_23_3.check_name(currVal_12,throwOnChange,false);
    this._Icon_23_3.detectChangesInternal(this,this._el_23,throwOnChange);
    this._Col_27_3.detectChangesInternal(this,this._el_27,throwOnChange);
    const currVal_16:any = '';
    this._Button_29_4.check_small(currVal_16,throwOnChange,false);
    const currVal_17:any = '';
    this._Button_29_4.check_clear(currVal_17,throwOnChange,false);
    const currVal_18:any = 'default';
    this._Button_29_4.check_color(currVal_18,throwOnChange,false);
    if (this._Button_29_4.detectChangesInternal(this,this._el_29,throwOnChange)) { this._appEl_29.componentView.markAsCheckOnce(); }
    const currVal_19:any = 'share-alt';
    this._Icon_31_3.check_name(currVal_19,throwOnChange,false);
    this._Icon_31_3.detectChangesInternal(this,this._el_31,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if ((this.numberOfChecks === 0)) { this._Button_13_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_21_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_29_4.context.ngAfterContentInit(); }
    }
    const currVal_0:any = this.context.$implicit.symbol;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_6,'innerHTML',this.viewUtils.sanitizer.sanitize(import69.SecurityContext.HTML,currVal_0));
      this._expr_0 = currVal_0;
    }
    const currVal_6:any = this._Icon_15_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_15,'hide',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = import4.interpolate(1,'\n           Favorite ',this.context.$implicit.favoritecount,'\n         ');
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setText(this._text_16,currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_13:any = this._Icon_23_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_23,'hide',currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = import4.interpolate(1,'\n           Like ',this.context.$implicit.likecount,'\n         ');
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setText(this._text_24,currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_20:any = this._Icon_31_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_31,'hide',currVal_20);
      this._expr_20 = currVal_20;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_15_3.context.ngOnDestroy();
    this._Icon_23_3.context.ngOnDestroy();
    this._Icon_31_3.context.ngOnDestroy();
  }
  private _handle_click_13_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.addfavorite($event,this.context.$implicit)) !== false);
    return (true && pd_0);
  }
  private _handle_click_21_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.addlike($event,this.context.$implicit)) !== false);
    return (true && pd_0);
  }
  private _handle_click_29_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.shareFb($event,this.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_MainTab22(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_MainTab22(viewUtils,parentInjector,declarationEl);
}